import { InMemoryDbService } from 'angular-in-memory-web-api';
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
      const products = [
        {id: 1, name: 'Badminton', price: 450, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://www.proprofs.com/quiz-school/topic_images/p18ku126q51c46fj81tg013m613nu3.png' },
        {id: 2, name: 'Football', price: 650, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://shop.savethechildren.org.uk/wp-content/uploads/2016/10/football-1.png'},
        {id: 3, name: 'Cricket Set', price: 5900, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://images-na.ssl-images-amazon.com/images/I/71TUNCQxJTL._SL1500_.jpg'},
        {id: 4, name: 'Basket Ball', price: 840, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://assets.primesport.com/prod/images/Generic%20Basketball%20Logo.png'},
        {id: 5, name: 'Volley Ball', price: 470, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://yt3.ggpht.com/-0zo3UN2TACg/AAAAAAAAAAI/AAAAAAAAAAA/2zANjbHjEZQ/s900-c-k-no-mo-rj-c0xffffff/photo.jpg'},
        {id: 6, name: 'Watch', price: 12000, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://content.rolex.com/is/image/Rolex/?src=is%7BRolex%2Fshadow_cellini_moonphase_39%3Flayer%3D1%26src%3D50776%26layer%3D2%26src%3D50771_p_39%26layer%3D3%26src%3D50769%7D&$rv55-watch-grid-retina$'},
        {id: 7, name: 'shoes', price: 1500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://rukminim1.flixcart.com/image/1408/1408/shoe/y/6/e/wonder-13-45-asian-grey-original-imaenr72gssfxrbj.jpeg?q=90'},
        {id: 8, name: 'Treadmill', price: 3500, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ',image: 'http://shop.lifefitness.com/UserFiles/Images/Products/F3-Treadmill-Go-Console-L.jpg'},
        {id: 9, name: 'Sports Cycle', price: 6800, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://5.imimg.com/data5/XC/LK/MY-24806022/sport-cycle-500x500.jpg'},
        {id: 10, name: 'Boxing gloves', price: 980, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'http://www.twinsfightgear.com/assets/images/BoxingGloves_bgvl3red.jpg'},
        {id: 11, name: 'Chess', price: 1400, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://cdn6.bigcommerce.com/s-5p6k1/product_images/e/plastic-chess-sets-banner-310__49082.jpg' },
        {id: 12, name: 'Table Tennis set', price: 1896, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://images-na.ssl-images-amazon.com/images/I/51xOvmxUgJL._SX355_.jpg'},
        {id: 13, name: 'Baseball Bat', price: 874, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://www.baseballsavings.com/wcsstore/CatalogAssetStore/Attachment/images/products/baseball/P30947/cfli-ap5albertpujolsblacknatural.jpg'},
        {id: 14, name: 'Dumbbells', price: 638, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://s7d2.scene7.com/is/image/dkscdn/16BFXUSLCTTCHDMBBSLC_is'},
        {id: 15, name: 'Badminton Net', price: 460, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'http://www.mantis-sport.com/images/stories/shop/product/TSM003_3M-Badminton_Net.png'},
        {id: 16, name: 'Cricket Ball', price: 150, description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam volutpat ante in tempor efficitur. Nulla sit amet tristique arcu, a finibus sem. Donec pulvinar suscipit lorem a iaculis. Maecenas non aliquet ipsum. ', image: 'https://cdn.shopify.com/s/files/1/1126/9634/products/Gray_Nicolls_Aut_4dc38d30198c3.jpeg?v=1457417337'}
      ];
      return {products};
    }
  }